"""mermaid — auto-generated concept-map diagrams.

Walks the master plan + daily lesson topics, builds a Mermaid graph
that captures topic dependencies and flow. Saves both as a `.mmd`
text file (portable) and as a standalone `.html` page that renders
the diagram client-side via the bundled Mermaid library (CDN at
unpkg, falls back to plain text if offline).

No LLM call — purely structural transform of existing manifest data.
"""
from __future__ import annotations

import json
from pathlib import Path


class MermaidTool:
    name = "mermaid"
    description = "Concept-map diagram (Mermaid) showing topic flow"

    def run(self, packet_dir: Path, manifest: dict):
        from . import ToolResult

        days = manifest.get("daily_lessons") or []
        cfg = manifest.get("config") or {}
        subject = cfg.get("subject", "Study Packet")
        if not days:
            return ToolResult(
                name=self.name, success=False, output_paths=[],
                detail="no daily lessons in manifest",
            )

        mmd_text = self._build_mermaid(subject, days)
        out_dir = packet_dir / "diagrams"
        out_dir.mkdir(exist_ok=True)

        mmd_path = out_dir / "topics.mmd"
        mmd_path.write_text(mmd_text, encoding="utf-8")

        html_path = out_dir / "topics.html"
        html_path.write_text(self._build_html(subject, mmd_text), encoding="utf-8")

        return ToolResult(
            name=self.name,
            success=True,
            output_paths=[mmd_path, html_path],
            detail=f"diagram with {len(days)} nodes",
        )

    # ─── Diagram construction ──────────────────────────────────────────

    def _build_mermaid(self, subject: str, days: list[dict]) -> str:
        """Build a Mermaid flowchart from the day list.

        Topics flow Day 1 → Day 2 → … → Exam. We also cluster days that
        share chapter prefixes so users see the topical shape.
        """
        lines = [
            "%% Auto-generated by bart — concept flow",
            "%% Drop into any markdown viewer that supports Mermaid",
            "",
            "flowchart TD",
            f"  subject([\"{self._escape(subject)}\"])",
            "  classDef learn fill:#fbf9f4,stroke:#c96442,color:#221f1b;",
            "  classDef practice fill:#f4f1ea,stroke:#9a4628,color:#221f1b;",
            "  classDef review fill:#e6e1d6,stroke:#3a342d,color:#221f1b;",
            "  classDef mock fill:#c96442,stroke:#9a4628,color:#fff;",
        ]

        node_ids = []
        for d in days:
            num = d.get("day", 0)
            topic = d.get("topic", f"Day {num}")
            focus = (d.get("focus") or "learn").lower()
            nid = f"d{num:02d}"
            node_ids.append((nid, focus))
            label = f"Day {num:02d}<br/>{self._escape(topic)}"
            lines.append(f'  {nid}["{label}"]:::{self._focus_class(focus)}')

        # Sequential edges
        if node_ids:
            lines.append(f"  subject --> {node_ids[0][0]}")
            for (a, _), (b, _) in zip(node_ids, node_ids[1:]):
                lines.append(f"  {a} --> {b}")
            lines.append(f"  {node_ids[-1][0]} --> exam([\"EXAM\"]):::mock")

        return "\n".join(lines) + "\n"

    @staticmethod
    def _focus_class(focus: str) -> str:
        return {
            "learn": "learn",
            "practice": "practice",
            "review": "review",
            "mock-exam": "mock",
            "mock_exam": "mock",
        }.get(focus, "learn")

    @staticmethod
    def _escape(s: str) -> str:
        # Mermaid label escapes — quotes break it; we replace with smart quotes.
        s = s.replace('"', "'").replace("\n", " ")
        # Limit length so labels don't blow up the diagram
        return s if len(s) < 80 else s[:77] + "..."

    # ─── HTML view ─────────────────────────────────────────────────────

    def _build_html(self, subject: str, mmd_text: str) -> str:
        from html import escape as html_escape
        # Self-rendering page using mermaid.js from unpkg. If offline, the
        # raw .mmd text is displayed below as a fallback.
        return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html_escape(subject)} — concept flow</title>
  <link rel="stylesheet" href="../packet.css">
  <style>
    .mermaid {{ background: var(--cream-hi, #fbf9f4); border: 1px solid var(--border, #d9d3c4);
                padding: 32px; border-radius: 12px; margin: 24px 0; }}
    .fallback {{ font-family: var(--font-mono, ui-monospace, monospace);
                 background: var(--code-bg, #f0ebde); padding: 16px;
                 border-radius: 8px; white-space: pre; overflow-x: auto;
                 font-size: 13px; }}
  </style>
</head>
<body>
  <div class="layout">
    <div></div>
    <div>
      <main class="content">
        <article>
          <h1>{html_escape(subject)} <span style="color:#c96442">.</span></h1>
          <p>Auto-generated topic flow. Day-by-day progression with focus type indicated by color.</p>
          <pre class="mermaid">
{mmd_text}
          </pre>
          <details>
            <summary>Raw Mermaid source</summary>
            <pre class="fallback">{html_escape(mmd_text)}</pre>
          </details>
        </article>
      </main>
    </div>
  </div>
  <script type="module">
    import mermaid from 'https://unpkg.com/mermaid@10/dist/mermaid.esm.min.mjs';
    mermaid.initialize({{ startOnLoad: true, theme: 'neutral', securityLevel: 'loose' }});
  </script>
</body>
</html>
"""
