"""SolverAgent — produces Part B (answer key) given Part A (problems).

Splits the practice-exam pipeline so:
  - Part A is generated by the Author (problems only, no solutions)
  - Part B is generated here, in parallel-friendly fashion, with no corpus

The Solver does not need the full corpus brief — just the problems plus
the notation card. Its prompt is small; its output is bulk.
"""
from __future__ import annotations

from .base import Agent


class SolverAgent(Agent):
    name = "solver"
    prompt_file = "solver.md"

    def solve(self, exam_part_a: str, notation_card: str, max_tokens: int = 12000) -> str:
        cfg = self.ctx.cfg
        user = [{
            "type": "text",
            "text": (
                f"Subject: {cfg.subject}\n\n"
                f"NOTATION CARD\n{notation_card}\n\n"
                f"PRACTICE EXAM (Part A — problems only)\n---\n{exam_part_a}\n---"
            ),
        }]
        return self.ctx.llm.complete(
            model=cfg.primary_model,
            system=self.system_prompt,
            user=user,
            max_tokens=max_tokens,
            label="solver",
            temperature=0.3,
        )
